// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nimfyuygvcebqsjjjmip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pbWZ5dXlndmNlYnFzampqbWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDEwMzEsImV4cCI6MjA2NTMxNzAzMX0.yEw1_zyxqz6-CDrY0uo_Iy0DZXNgCC9XYe2hcVG-ifo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);